-- Extraido de: https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/icons.lua
-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file:
-- https://mathew-kurian.github.io/CharacterMap/ find more here:
-- https://www.nerdfonts.com/cheat-sheet

vim.g.use_nerd_icons = false
if vim.fn.has "unix" == 1 or vim.g.use_nerd_icons then
    return {
        -- CMP
        cmp_kind = {
            Namespace = "󰌗",
            Text = "󰉿",
            Method = "󰆧",
            Function = "󰆧",
            Constructor = "",
            Field = "󰜢",
            Variable = "󰀫",
            Class = "󰠱",
            Interface = "",
            Module = "",
            Property = "󰜢",
            Unit = "󰑭",
            Value = "󰎠",
            Enum = "",
            Keyword = "󰌋",
            Snippet = "",
            Color = "󰏘",
            File = "󰈚",
            Reference = "󰈇",
            Folder = "󰉋",
            EnumMember = "",
            Constant = "󰏿",
            Struct = "󰙅",
            Event = "",
            Operator = "󰆕",
            TypeParameter = "󰊄",
            Table = "",
            Object = "󰅩",
            Tag = "",
            Array = "[]",
            Boolean = "",
            Number = "",
            Null = "󰟢",
            String = "󰉿",
            Calendar = "",
            Watch = "󰥔",
            Package = "",
            Copilot = "",
            Codeium = "",
            TabNine = "",
        },
        -- NVIM-TREE
        nvimtree_glyphs = {
            default = "󰈚",
            symlink = "",
            folder = {
                default = "",
                empty = "",
                empty_open = "",
                open = "",
                symlink = "",
                symlink_open = "",
                arrow_open = "",
                arrow_closed = "",
            },
            git = {
                unstaged = "",
                staged = "",
                unmerged = "",
                renamed = "󰄾",
                untracked = "",
                deleted = "",
                ignored = "",
            },
        },
        -- MASON
        mason_icons = {
            package_pending = " ",
            package_installed = "󰄳 ",
            package_uninstalled = " 󰚌",
        },
        -- DIAGNOSTICS
        diagnostics = {
            error = "",
            -- error = "󰅚",
            warning = "",
            -- warning = "",
            info = "",
            -- info = "",
            hint = "󰌵",
            -- hint = "󰌶",
        },
        -- Miscelaneos
        git = {
            Add = "",
            AddOutline = "",
            Mod = "柳",
            ModOutline = "",
            Remove = "",
            RemoveOutline = "",
            Ignore = "",
            Rename = "",
            Diff = "",
            Repo = "",
            Octoface = "",
        },
        ui = {
            ArrowClosed = "",
            ArrowOpen = "",
            Lock = "",
            Circle = "",
            BigCircle = "",
            BigUnfilledCircle = "",
            Close = "",
            NewFile = "",
            Search = "",
            Lightbulb = "",
            Project = "",
            Dashboard = "",
            History = "",
            Comment = "",
            Bug = "",
            Code = "",
            Telescope = "",
            TelescopeCaret = "",
            Gear = "",
            Package = "",
            List = "",
            SignIn = "",
            SignOut = "",
            Check = "",
            Fire = "",
            Note = "",
            BookMark = "",
            Pencil = "",
            -- ChevronRight = "",
            ChevronRight = ">",
            Table = "",
            Calendar = "",
            CloudDownload = "",
        },
        misc = {
            Robot = "ﮧ",
            Squirrel = "",
            Tag = "",
            Watch = "",
            Smiley = "ﲃ",
            Package = "",
            CircuitBoard = "",
        },
    }
end
